version: "3"
services:
  db:
    image: mongo:3.4
    volumes:
      - .mongodb:/data/db

  backend:
    build: backend
    command: /backend/setup.sh
    volumes:
      - ./backend:/backend
    ports:
      - 8008:3003
    depends_on:
     - db

  frontend:
    build: frontend
    command: /frontend/setup.sh
    volumes:
      - ./frontend:/frontend
    ports:
      - 8080:8080
    depends_on:
     - backend
     